twist_mux:
  ros__parameters:
    use_stamped: true
    out_stamped: true
    output_topic: cmd_vel_out
    topics:
      navigation:
        topic   : /diff_cont/cmd_vel
        timeout : 0.5
        priority: 100
      tracker:
        topic   : cmd_vel_tracker
        timeout : 0.5
        priority: 20
      joystick:
        topic   : cmd_vel_joy
        timeout : 0.5
        priority: 100